### ISSUE TITLE
[bug]:evil-pinyin-mode: Wrong type argument: keymapp, nil

### ISSUE THREAD

**Issue by yqu212** [laishulu/evil-pinyin#2]
I just updated to the latest version from github.

**Comment by laishulu** [comment]
不能复现~~~~。
能不能这么启动emacs：  `emacs --debug-init`
然后把出错信息发给我看看呢？

**Comment by yqu212** [comment]
我是这么加载的。
```emacs-lisp
(use-package evil-pinyin
    :init
    (global-evil-pinyin-mode))
```

**Comment by laishulu** [comment]
正常应该放在 `:config` 里面的。

**Comment by yqu212** [comment]
呃。昏头了。多谢。

**Comment by laishulu** [comment]
那没问题了？

**Comment by yqu212** [comment]
还是报错。
加载
```
(use-package evil-pinyin
    :config
    (global-evil-pinyin-mode))
```
启动时报错
> Error (use-package): evil-pinyin/:config: Wrong type argument: keymapp, nil

**Comment by laishulu** [comment]
在命令下，启动 `emacs --debug-init`
那样可以给我详细的信息。

之前没错么？

**Comment by yqu212** [comment]
之前没错。等下，我debug一下。

**Comment by laishulu** [comment]
找到了

**Comment by laishulu** [comment]
等我提交

**Comment by yqu212** [comment]
好的

**Comment by laishulu** [comment]
有一行废代码，忘了删

**Comment by laishulu** [comment]
提交了~~

**Comment by laishulu** [comment]
请测试反馈

**Comment by yqu212** [comment]
最新版还是一样的问题。等下贴debug信息。

**Comment by laishulu** [comment]
我这里复现了。等等

**Comment by laishulu** [comment]
等我消息~~~

**Comment by yqu212** [comment]
> Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
  define-key(nil [remap evil-find-char] find-char)
  evil-pinyin-mode()
  global-evil-pinyin-mode()
  (progn (global-evil-pinyin-mode) (run-hooks 'use-package--evil-pinyin--post-config-hook))
  (if (run-hook-with-args-until-failure 'use-package--evil-pinyin--pre-config-hook) (progn (global-evil-pinyin-mode) (run-hooks 'use-package--evil-pinyin--post-config-hook)))
 

另外，生成autoload要时报错Error loading autoloads: (void-function evil-define-motion)

**Comment by yqu212** [comment]
好的

**Comment by laishulu** [comment]
已经修正了

**Comment by yqu212** [comment]
我马上试试。

**Comment by yqu212** [comment]
正常了。多谢。
