### ISSUE TITLE
[bug] Error loading autoloads: (void-function evil-define-motion)

### ISSUE THREAD

**Issue by yqu212** [laishulu/evil-pinyin#3]
功能上似乎没什么影响。

**Comment by laishulu** [comment]
我generate autoload的时候，是正常的。
请问如何复现？

**Comment by laishulu** [comment]
我这边可以正常生产：

```

;;;***

(autoload 'evil-pinyin-mode "evil-pinyin" "\
Evil search or find Chinese characters by pinyin.

\(fn &optional ARG)" t nil)

(defvar global-evil-pinyin-mode nil "\
Non-nil if Global Evil-Pinyin mode is enabled.
See the `global-evil-pinyin-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-evil-pinyin-mode'.")

(custom-autoload 'global-evil-pinyin-mode "evil-pinyin" nil)

(autoload 'global-evil-pinyin-mode "evil-pinyin" "\
Toggle Evil-Pinyin mode in all buffers.
With prefix ARG, enable Global Evil-Pinyin mode if ARG is positive;
otherwise, disable it.  If called from Lisp, enable the mode if
ARG is omitted or nil.

Evil-Pinyin mode is enabled in all buffers where
`evil-pinyin-mode' would do it.
See `evil-pinyin-mode' for more information on Evil-Pinyin mode.

\(fn &optional ARG)" t nil)
```

**Comment by yqu212** [comment]
这个问题只在装完包之后加载的时候出现了。后面就没再报过这个错。autoloads正常生成了。单独加载autoloads的时候也没问题。

可能是spacemacs的问题吧。也许是第一次加载的时候还没有加载evil。先别管了。

**Comment by yqu212** [comment]
呃。我生成的autoloads和你的不一样。

;;; evil-pinyin-autoloads.el --- automatically extracted autoloads
;;
;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))


;;;### (autoloads nil "evil-pinyin" "evil-pinyin.el" (0 0 0 0))
;;; Generated autoloads from evil-pinyin.el

(define-namespace evil-pinyin- (defvar with-search t "Enable the /search/ feature.") (make-variable-buffer-local 'evil-pinyin-with-search) (defvar with-traditional nil "Include traditional Chinese.") (defvar with-punctuation t "Include Chinese punctuation.") (defun -build-regexp (thing) "Build regexp form THING for search." (cond ((integerp thing) (pinyinlib-build-regexp-char thing (not with-punctuation) with-traditional)) ((stringp thing) (pinyinlib-build-regexp-string thing (not with-punctuation) with-traditional)))) (evil-define-motion find-char (count char) "Move to the next COUNT'th occurrence of CHAR." :type inclusive (interactive "<c><C>") (setq count (or count 1)) (let ((fwd (> count 0))) (setq evil-last-find (list #'find-char char fwd)) (when fwd (forward-char)) (let ((case-fold-search nil)) (unless (prog1 (search-forward-regexp (-build-regexp char) (unless evil-cross-lines (if fwd (line-end-position) (line-beginning-position))) t count) (when fwd (backward-char))) (user-error "Can't find %c" char))))) (evil-define-motion find-char-backward (count char) "Move to the previous COUNT'th occurrence of CHAR." :type exclusive (interactive "<c><C>") (find-char (- (or count 1)) char)) (evil-define-motion find-char-to (count char) "Move before the next COUNT'th occurrence of CHAR." :type inclusive (interactive "<c><C>") (unwind-protect (progn (find-char count char) (if (> (or count 1) 0) (backward-char) (forward-char))) (setcar evil-last-find #'find-char-to))) (evil-define-motion find-char-to-backward (count char) "Move before the previous COUNT'th occurrence of CHAR." :type exclusive (interactive "<c><C>") (find-char-to (- (or count 1)) char)) (evil-define-motion repeat-find-char (count) "Repeat the last find COUNT times." :type inclusive (setq count (or count 1)) (if evil-last-find (let ((cmd (car evil-last-find)) (char (nth 1 evil-last-find)) (fwd (nth 2 evil-last-find)) evil-last-find) (when (< count 0) (setq count (- count) fwd (not fwd))) (and (eq cmd #'find-char-to) evil-repeat-find-to-skip-next (= count 1) (or (and fwd (or (= (char-after (1+ (point))) char) (string-match-p (-build-regexp char) (string (char-after (1+ (point))))))) (and (not fwd) (or (= (char-before) char) (string-match-p (-build-regexp char) (string (char-before)))))) (setq count (1+ count))) (funcall cmd (if fwd count (- count)) char) (unless (nth 2 evil-last-find) (setq evil-this-type 'exclusive))) (user-error "No previous search"))) (evil-define-motion repeat-find-char-reverse (count) "Repeat the last find COUNT times in the opposite direction." :type inclusive (repeat-find-char (- (or count 1)))) (defun -snipe-process-key (key) "Process the snipe KEY." (let ((regex-p (assoc key evil-snipe-aliases)) (keystr (char-to-string key))) (cons keystr (if regex-p (elt regex-p 1) (if mode (-build-regexp keystr) keystr))))) (defun evil-snipe--process-key-advice (fn key) "Advice for FN evil-snipe--process-key with ARGS args." (if mode (funcall #'-snipe-process-key key) (funcall fn key))) (defun evil-ex-pattern-regex-advice (fn &rest args) "Advice for FN evil-ex-pattern-regex with ARGS args." (let ((re (apply fn args))) (if (and mode re mode with-search (not (string-match-p "[.*+?[\\$]" re))) (-build-regexp re) re))) :autoload (define-minor-mode mode "Evil search or find Chinese characters by pinyin." :init-value nil :keymp 'evil-pinyin-mode-keymap (advice-add 'evil-ex-pattern-regex :around #'evil-ex-pattern-regex-advice) (when (featurep 'evil-snipe) (advice-add 'evil-snipe--process-key :around #'evil-snipe--process-key-advice)) (if (and mode evil-motion-state-local-map) (progn (define-key evil-motion-state-local-map [remap evil-find-char] #'find-char) (define-key evil-motion-state-local-map [remap evil-find-char-backward] #'find-char-backward) (define-key evil-motion-state-local-map [remap evil-find-char-to] #'find-char-to) (define-key evil-motion-state-local-map [remap evil-find-char-to-backward] #'find-char-to-backward) (define-key evil-motion-state-local-map [remap evil-repeat-find-char] #'repeat-find-char) (define-key evil-motion-state-local-map [remap evil-repeat-find-char-reverse] #'repeat-find-char-reverse)) (when evil-motion-state-local-map (define-key evil-motion-state-local-map [remap evil-find-char] nil) (define-key evil-motion-state-local-map [remap evil-find-char-backward] nil) (define-key evil-motion-state-local-map [remap evil-find-char-to] nil) (define-key evil-motion-state-local-map [remap evil-find-char-to-backward] nil) (define-key evil-motion-state-local-map [remap evil-repeat-find-char] nil) (define-key evil-motion-state-local-map [remap evil-repeat-find-char-reverse] nil)))) :autoload (define-globalized-minor-mode global-evil-pinyin-mode evil-pinyin-mode evil-pinyin-mode) (defun clear nil "Clear all pollutions." (advice-remove 'evil-ex-pattern-regex #'evil-ex-pattern-regex-advice) (when (featurep 'evil-snipe) (advice-remove 'evil-snipe--process-key #'evil-snipe--process-key-advice))))

;;;***

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; evil-pinyin-autoloads.el ends here

**Comment by yqu212** [comment]
另外，还有一个怪问题。不知道跟上面的autoload有没有关系。 

这个包在dumper模式下面不能用use-package加载。这是我遇到的第一个出现这种问题的包。在非dumper模式下面就是正常加载。

**Comment by yqu212** [comment]
我看了一下load-path，evil-pinyin不在里面。不知道是哪里出了问题。

**Comment by yqu212** [comment]
@laishulu 刚才确认了一下。别的包也有这个问题。是我自己配置的问题。

**Comment by laishulu** [comment]
dumper是不是要从melpa下载包？
这个包还在审核中，没进melpa呢~~

**Comment by yqu212** [comment]
问题我解决了。换成emacs27就正常了。现在可以正常使用了。应该是emacs28的什么bug吧。

**Comment by laishulu** [comment]
你可真激进。

现在的稳定版是26，你都用到28了。

**Comment by yqu212** [comment]
我是spacemacs用户。spacemacs启动速度真的受不了。自己优化也太花功夫。spacemacs有pdumper就用下来了。而这个特性只有emacs27才有。所以一直在用emacs-git。没出什么大问题，所以就没换，就这样用到了emacs28。

**Comment by yqu212** [comment]
~呃。 问题还在。是spacemacs的问题。它dump的时候没把新装的包加进load-path里。~
问题解决了。emacs没问题，spacemacs也没问题，问题出在我的用法上面。spacemacs/dump-emacs生成的dump文件以.new结尾，没有自动替换正在使用的dump文件，而我一直使用旧的dump文件，当然不会加载新装的包。

**Comment by laishulu** [comment]
用doom啊。。。
doom秒开，所有的包都是延迟加载的。
我都那emacs当vim用的，随用随开。
据说emacs mac port不支持多emacs client
没试过，没那个需求。

spacemacs用起来配置太乱了，
doom清晰简洁美感，这里是我的配置目录
doom配置只要三步（我的也是这样）：
1. init.el 中选择doom内置的模块
2. packages.el 中声明自用非内置模块
3. config.el 中配置模块
https://github.com/laishulu/conf/tree/master/emacs

**Comment by yqu212** [comment]
我也眼馋doom。不过doom下包是个大问题。之前我在论坛上也说起过。另外，现在迁移起来成本也太高了。不划算。

其实spacemacs我用起来感觉还可以。模块化做得很好。功能也齐全。就是lazy load做得很差。有些家伙贡献配置的时候根本不考虑加载时间。优化起来有点烦。慢慢优化吧。现在启动要10s。400个包。也能接受。

用上pdumper之后这些烦恼已经没了。感觉很好。不用考虑lazy load，安装新包的时候省心。启动时间只与硬盘性能相关。打开之后一切就绪，没有加载的问题。我觉得这点是无论怎么lazy load也做不到的体验。
